### ISSUE TITLE
error: ‘IsKaldiError’ is not a member of ‘kaldi’

### ISSUE THREAD

**Issue by helson73** [dmitriy-serdyuk/kaldi-python#7]
Hi, 
I tried to run 'python setup.py install' , but following error rised.

error: ‘IsKaldiError’ is not a member of ‘kaldi’

How to fix it?

Thanks.

**Comment by helson73** [comment]
I just successfully compiled kaldi-python by commenting all lines include 'IsKaldiError'.
It seems kaldi header files do not have such function or definition.

**Comment by dmitriy-serdyuk** [comment]
Probably kaldi was changed, either try older version of kaldi or comment it out on your own risk. A proper solution would be to find what is a new name of `IsKaldiError`.

**Comment by helson73** [comment]
Thanks!

**Comment by dmitriy-serdyuk** [comment]
It is still an issue. I'll try to fix it when I have time.
